# -*- coding: utf-8 -*-
"""NLTK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SQ2pk4QfqL8MpBiFC_ac8Snec72XoHbL
"""

corpus = [
          'Various sectors of life have changed due to the COVID pandemic.',
          'One of the sectors affected is the education sector.',
          'Education is an important sector that requires appropriate solutions and policie',
          'One of them is by studying at home.',
          'Studying at home is a solution that is very suitable and relevant to the pandemic conditions.',
          'First by studying at home the number of virus spread due to interactions between people can be reduced.',
          'The spread of the virus can be through the air we breathe.',
          'Although this can be overcome by wearing a mask and washing hands.',
          'But surely sometimes we forget and ignore it.',
          'Students and teachers can interact through online learning media.',
          'Students and teachers can interact through online learning media',
          'Then studying at home requires students to be more active and creative in solving their own problems.',
          'In the latest curriculum which plays the biggest role is the activeness of students and teachers just to guide them.',
          'With this condition students will get used to being more independent and creative in teaching and learning activities',
          'So that interactions with friends and teachers can still occur through online media.',
          'In this way students will gain learning knowledge and also the ability to face various other problems later.',
          'Studying at home can improve and enhance family relationships.',
          'With a lot of time spent at home.',
          'it means that a lot of time is also spent with loved ones.',
          'Children will ask their parents for help in learning and parents will help them.'
]

corpus

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
vectorized_X = vectorizer.fit_transform(corpus).todense()
vectorized_X

vectorizer.get_feature_names_out()

from sklearn.metrics.pairwise import euclidean_distances

for i in range(len(vectorized_X)):
    for j in range(i, len(vectorized_X)):
        if i == j:
            continue
        jarak = euclidean_distances(vectorized_X[i], vectorized_X[j])
        print(f'Jarak dokumen {i+1} dan {j+1}: {jarak}')