# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pPBVMxWItVUFXtRHxbK1ea0wwQmA7X-
"""

import numpy as np
import csv
import pandas as pd

import tweepy
import re
from textblob import TextBlob

access_token= "252355250-a0HgoQDScEVw5GjhzrLDEOYHbK0ngj7f6vwRTAS3"
access_token_secret= "ceP8O2WqBEc3tHwMoYetc3QsN1z7WwlAfazj6UulTJqPy"
api_key= "hPCUgkmOBKcd2LAJ9lCTRFYfA"
api_key_secret= "diDKq4zovrOGZdXDBm9H5gpaMvchIBXe4ssi64hdjyev73Td1s"

auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

hasilSearch = api.search(q="xl", lang="en", count=100)

hasilAnalisis = []

for tweet in hasilSearch:
    tweet_properties = {}
    tweet_properties["Tanggal_tweet"] = tweet.created_at
    tweet_properties["Pengguna"] = tweet.user.screen_name
    tweet_properties["Isi_tweet"] = tweet.text
    tweet_bersih = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)"," ",tweet.text).split())
  
      
    analysis = TextBlob(tweet_bersih)
    
    if analysis.sentiment.polarity > 0.0:
        tweet_properties["Sentiment"] = "Positif"
    elif analysis.sentiment.polarity == 0.0:
        tweet_properties["Sentiment"] = "Netral"
    else:
        tweet_properties["Sentiment"] = "Negatif"

    if tweet.retweet_count >0:
        if tweet_properties not in hasilAnalisis:
            hasilAnalisis.append(tweet_properties)
    else :
        hasilAnalisis.append(tweet_properties)

tweet_positif = [t for t in hasilAnalisis if t["Sentiment"]=="Positif"]
tweet_netral = [t for t in hasilAnalisis if t["Sentiment"]=="Netral"]
tweet_negatif = [t for t in hasilAnalisis if t["Sentiment"]=="Negatif"]

print("hasilAnalisis")
print("Positif: ", len(tweet_positif), "({}%)".format(100*len(tweet_positif)/len(hasilAnalisis)))
print("Netral: ", len(tweet_netral), "({}%)".format(100*len(tweet_netral)/len(hasilAnalisis)))
print("Negatif: ", len(tweet_negatif), "({}%)".format(100*len(tweet_negatif)/len(hasilAnalisis)))